# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Si2chipCloud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempmeasure',
            old_name='temprature',
            new_name='temperature',
        ),
    ]
