# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Si2chipCloud', '0002_auto_20160201_1005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MotionSensor',
            new_name='MotionMeasure',
        ),
    ]
