# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Si2chipCloud', '0003_auto_20160205_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionmeasure',
            name='motion',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
